@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class users {
   enabled: boolean
   last_password_reset_date: timestamp(6)
   activation_token: varchar(255)
   address: varchar(255)
   email: varchar(255)
   first_name: varchar(255)
   last_name: varchar(255)
   password: varchar(255)
   username: varchar(255)
   id: bigint
}
class video_comments {
   created_at: timestamp(6)
   user_id: bigint
   version: bigint
   video_post_id: bigint
   text: varchar(2000)
   id: bigint
}
class video_likes {
   created_at: timestamp(6)
   user_id: bigint
   video_id: bigint
   id: bigint
}
class video_posts {
   created_at: timestamp(6)
   owner_id: bigint
   views: bigint
   description: varchar(2000)
   location: varchar(255)
   thumbnail_path: varchar(255)
   title: varchar(255)
   video_path: varchar(255)
   id: bigint
}
class video_tags {
   video_id: bigint
   tag: varchar(255)
}

video_comments  -[#595959,plain]-^  users          : "user_id:id"
video_comments  -[#595959,plain]-^  video_posts    : "video_post_id:id"
video_likes     -[#595959,plain]-^  users          : "user_id:id"
video_likes     -[#595959,plain]-^  video_posts    : "video_id:id"
video_posts     -[#595959,plain]-^  users          : "owner_id:id"
video_tags      -[#595959,plain]-^  video_posts    : "video_id:id"
@enduml
